title: Foodie's Pick,
logo: /assets/img/logo.png
description: A personal Guide to good restaurants and bars.
show_downloads: true
google_analytics:
#theme: jekyll-theme-minimal

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 